#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
設定模組初始化
"""

from .config import (
    LLAMA_SERVER,
    LLAMA_SERVER_URL,
    MODEL_NAME,
    MAX_TOKENS,
    TEMPERATURE,
    TOP_P,
    UI_WIDTH,
    UI_HEIGHT,
    MEMORY_FILE,
    PERSONALITY_FILE,
    THOUGHTS_FILE,
    DECISIONS_FILE,
    EVOLUTION_FILE,
    MAX_MEMORY,
    MAX_MEMORY_MESSAGES,
    MEMORY_SUMMARY_TRIGGER,
    DEFAULT_PERSONALITY,
    SCREENSHOT_INTERVAL,
    REFLECTION_INTERVAL,
    AUTONOMOUS_CHECK_INTERVAL,
)